### ISSUE TITLE
Round Edges

### ISSUE THREAD

**Issue by Michikow10** [SisfoK/classless-css#3]
- round edges
Pada button, section materi, dan alert, boleh diubah cornernya menjadi rounded corners atau edges, tetapi jangan sampai terlalu round

**Comment by deovaliandro** [comment]
https://github.com/SisfoK/classless-css/blob/4777c39220190736d39dfddf5b8e26a242359310/main.scss#L120
https://github.com/SisfoK/classless-css/blob/4777c39220190736d39dfddf5b8e26a242359310/main.scss#L295

Seperti itu?

**Comment by Michikow10** [comment]
Iyaa kak, bisaa
