### ISSUE TITLE
Page (Materi)

### ISSUE THREAD

**Issue by Michikow10** [SisfoK/classless-css#5]
- materi (page)
Ketika membuka page materi, misalnya Struktur Dasar pada tulisan P.Pemrograman, dapat ditambahkan icon untuk memilih materi lain pada tulisan P.Pemrograman agar tidak perlu untuk kembali pada main page untuk memilih materi lain pada tulisan yang sama

**Comment by deovaliandro** [comment]
ahh betul tapi sebenarnya itu bukan bagian dari css, itu adanya di https://github.com/SisfoK/sisfok.github.io, tapi bagus juga, tunggu saya bertapa di gua sakti.. 🤸🏼‍♂️

**Comment by Michikow10** [comment]
Heheee iya kak, mulai menjurus ke UX wkwk

**Comment by deovaliandro** [comment]
ditunggu kontribusinya.. :D
